inherit_gem:
  rubocop-shopify: rubocop.yml

AllCops:
  NewCops: enable
  SuggestExtensions: false

Naming/FileName:
  Exclude:
    - 'lib/blake3-rb.rb'

Style/GlobalVars:
  Exclude:
    - 'ext/digest/blake3_ext/extconf.rb'
