#!/bin/bash

set -euo pipefail

repo="$1"
tag="$2"

release_id=$(curl -s "https://api.github.com/repos/$repo/releases/tags/$tag" | jq -r .id)

assets=$(curl -s "https://api.github.com/repos/$repo/releases/$release_id/assets" | jq -c '.[]')

for asset in $(echo "${assets}" | jq -r '. | @base64'); do
  _jq() {
    echo ${asset} | base64 --decode | jq -r ${1}
  }

  url=$(_jq '.browser_download_url')
  name=$(_jq '.name')
  mkdir -p pkg
  echo "Saving artifact to pkg/${name}..."
  curl -sLo "pkg/${name}" "${url}"
done

echo "Done!"
