---
  name: Lint

  on:
    push:
      branches:
        - main

    pull_request:

  jobs:
    lint:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3

        - uses: oxidize-rb/actions/setup-ruby-and-rust@v1
          with:
            rustup-toolchain: "1.73"
            ruby-version: "3.2"
            bundler-cache: true
            cargo-cache: true
            cache-version: v1

        - name: Rubocop
          run: bundle exec rake rubocop

        - name: Clippy
          run: cargo clippy -- -D warnings

        - name: Cargo
          run: cargo fmt --check
